### ISSUE TITLE
CMS Admin fails to load on `astro dev` on windows

### ISSUE THREAD

**Issue by codelastnight** [delucis/astro-netlify-cms-starter#2]
CMS fails to load only in dev. works when deployed to netlify.
when loading admin page, I get this error:
```
[vite] Internal server error: Failed to resolve import "C:UserssimonDocumentsGitHubportfolio2srcstylelog.css" from "\admin?html-proxy&index=0.js". Does the file exist?
```

### To replicate:
on windows 10, with node 16, powershell 7
fresh clone of astro netlify cms starter
use `pnpm i`
then `pnpm run dev`

### workaround
use wsl instead of powershell (this works perfectly)

I believe that its some issue with the way windows handles files

**Comment by delucis** [comment]
Hi @codelastnight! Thanks for the report. I don’t have a Windows machine to test on, so debugging this on my end will likely be tricky. Looks like `C:UserssimonDocumentsGitHubportfolio2srcstylelog.css` is missing the slash separators and _maybe_ `\b` got interpreted as a backspace? 🤔 

My guess would be this line might be the issue but would have expected Node’s `join` to handle this correctly.

https://github.com/delucis/astro-netlify-cms/blob/d6e1a3d6cbd5bc00fe260f3ccd30037152281735/integration/vite-plugin-admin-dashboard.ts#L47

Any help debugging further would be appreciated!

**Comment by codelastnight** [comment]
I was able to get it to work by, unintuitively, not using `join()` 😅 

in vite-plugin-admin-dashboard, on line 47:
```
imports.push(`import ${name} from '/${filename}';`);
```
instead of 
```
imports.push(`import ${name} from '${join(projectRoot, style)}';`);

```
is it important on linux to include the projectRoot?
perhaps vite already assumes all file imports with a unix syntax so backslashes confuses it 🤔

**Comment by delucis** [comment]
Fixed in https://github.com/delucis/astro-netlify-cms/pull/23
