### ISSUE TITLE
Image optimizations (vite-imagetools)

### ISSUE THREAD

**Issue by eur2** [delucis/astro-netlify-cms-starter#3]
Hello, nice template! Would it be useful to add directly optimizations for images used in markdown in the template? With vite-imagetools? Thanks a lot

**Comment by delucis** [comment]
Does vite-imagetools work in Astro projects? I know there are some dedicated Astro-specific optimisations but would be curious to hear more.

I haven't spent much time on this template — it was just adapted from Astro's default blog example — and should probably be kept as simple as possible as a lightweight example of Astro and the Netlify CMS integration.
